CREATE TABLE IF NOT EXISTS thumbnails (
  id INT AUTO_INCREMENT PRIMARY KEY,
  video_id INT NOT NULL UNIQUE,
  filename VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (video_id) REFERENCES videos(id) ON DELETE CASCADE
)
