ALTER TABLE videos ADD COLUMN duration FLOAT DEFAULT NULL;
ALTER TABLE videos ADD COLUMN width INT DEFAULT NULL;
ALTER TABLE videos ADD COLUMN height INT DEFAULT NULL;
ALTER TABLE videos ADD COLUMN codec VARCHAR(50) DEFAULT NULL;
ALTER TABLE videos ADD COLUMN audio_codec VARCHAR(50) DEFAULT NULL;
ALTER TABLE videos ADD COLUMN bitrate BIGINT DEFAULT NULL
